apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contaapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/martino-lucas95/mk-contaapp.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: contaapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
