apiVersion: v1
kind: Secret
metadata:
  name: contaapp-secrets
  namespace: contaapp
type: Opaque
stringData:
  DB_HOST: postgres.default.svc.cluster.local
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: "yJb1mB&tJy8w"
  DB_NAME: contaapp
  JWT_SECRET: "CAMBIA_ESTO_jwt_secret_64chars_minimo_en_produccion_now"
  JWT_EXPIRES_IN: "7d"
  JWT_REFRESH_SECRET: "CAMBIA_ESTO_refresh_secret_64chars_minimo_diferente"
  JWT_REFRESH_EXPIRES_IN: "30d"
  ENCRYPTION_KEY: "contaapp_prod_key_32bytes_secret"
  NODE_ENV: production
  PORT: "3000"
  FRONTEND_URL: "https://contaapp.mkstudios.net"
